name: CI

on: [push, pull_request]

jobs:
  build-and-upload:
    runs-on: ubuntu-20.04
    env:
        DEBIAN_FRONTEND: "noninteractive"
        CONAN_USER_HOME: "${{ github.workspace }}/"
        CONAN_NON_INTERACTIVE: 1
        CONAN_USERNAME: "blixt"
        CONAN_GIT_REF: "${{ github.ref }}"
        CONAN_UPLOAD: "${{ secrets.CONAN_UPLOAD }}"
        CONAN_LOGIN_USERNAME: "${{ secrets.CONAN_LOGIN_USERNAME_UPLOAD }}"
        CONAN_PASSWORD: "${{ secrets.CONAN_PASSWORD_UPLOAD }}"
        CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
        CONAN_STABLE_BRANCH_PATTERN: "stable/*"
        CONAN_SYSREQUIRES_MODE: "enabled"
        CONAN_ARCHS:  "x86_64"
        CONAN_GCC_VERSIONS: "7"
        CONAN_BUILD_TYPES: "Release"
        CONAN_USE_DOCKER: 1
        CONAN_DOCKER_IMAGE: "conanio/gcc7"
        CONAN_SHARED_OPTION_NAME: "False"
    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        shell: bash
        run: |
          pip install --upgrade pip conan
          python --version
          pip --version
          conan --version
          pip install conan-package-tools
          pip install git+https://github.com/blixttech/cpt-helpers.git

      - name: Build and Upload
        shell: bash
        run: python build.py
